import { defineConfig } from 'vite';
import path from 'path';

// https://vitejs.dev/config
export default defineConfig({
  resolve: {
    alias: {
      '@shared': path.resolve(__dirname, './src/shared'),
    },
  },
  build: {
    outDir: '.vite/build',
    emptyOutDir: false,
    target: 'node18',
    lib: {
      entry: 'electron/main/index.ts',
      formats: ['cjs'],
      fileName: () => 'index.js',
    },
    rollupOptions: {
      external: [
        'electron',
        'better-sqlite3',
        'sharp',
        'exiftool-vendored',

        '@ffmpeg-installer/ffmpeg',
        '@ffprobe-installer/ffprobe',
        '@xenova/transformers',
        'onnxruntime-node',
        'archiver',
        'chokidar',
        '@sentry/electron',
        'electron-updater',
        // Node.js built-ins
        'fs',
        'fs/promises',
        'path',
        'crypto',
        'http',
        'https',
        'url',
        'util',
        'os',
        'child_process',
        'stream',
        'events',
        'buffer',
        'querystring',
        'zlib',
        'net',
        'tls',
        'dns',
        'dgram',
        'cluster',
        'module',
        'readline',
        'repl',
        'tty',
        'v8',
        'vm',
        'worker_threads',
        'perf_hooks',
        'async_hooks',
        'inspector',
        'trace_events',
        'assert',
        'constants',
        'string_decoder',
        'timers',
        'console',
        'process',
      ],
    },
  },
});
